/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    jacoco
    alias(libs.plugins.sonarqube)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)
    testImplementation(libs.junitParams)
    testImplementation(libs.mockito)

    testRuntimeOnly(libs.junitEngine)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.lanterna)
}

// Apply a specific Java toolchain to ease working on different environments.
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

application {
    // Define the main class for the application.
    mainClass = "org.brayancaro.Menu"
}

tasks.getByName("run", JavaExec::class) {
 standardInput = System.`in`
}

tasks.test {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport) // report is always generated after tests run
}
tasks.jacocoTestReport {
    dependsOn(tasks.test) // tests are required to run before generating the report

    reports {
      xml.required = true
    }
}

sonar {
  properties {
    property("sonar.projectKey", "BrayanCaro_ProyectoFinal")
    property("sonar.organization", "brayancaro")
    property("sonar.host.url", "https://sonarcloud.io")
  }
}
