/*
 * This source file was generated by the Gradle 'init' task
 */
package org.brayancaro;

import java.io.IOException;
import java.security.SecureRandom;

import com.googlecode.lanterna.screen.TerminalScreen;
import com.googlecode.lanterna.terminal.DefaultTerminalFactory;

import jakarta.validation.Validation;

public class App {
    public static void main(String[] args) throws IOException {
        var validatorFactory = Validation.buildDefaultValidatorFactory();
        var validator = validatorFactory.getValidator();

        var defaultTerminalFactory = new DefaultTerminalFactory();

        try (var terminal = defaultTerminalFactory.createTerminal();
                var screen = new TerminalScreen(terminal)) {

            (new Menu())
                    .random(new SecureRandom())
                    .screen(screen)
                    .validator(validator)
                    .play();
        }

    }
}
